config/routes.rb
Rails.application.routes.draw do

  root "matters#new"

  resources :staffings
  resources :matters

end

app/models/lawfirm.rb
class Lawfirm < ActiveRecord::Base
end

app/models/matter.rb
class Matter < ActiveRecord::Base
  belongs_to :lawfirm
end

app/models/staffing.rb
class Staffing < ActiveRecord::Base
  belongs_to :lawfirm
  belongs_to :matter
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/matters_controller.rb
class MattersController < ApplicationController
  before_action :set_matter, only: [:show, :edit, :update, :destroy]
  before_action :set_staffing, only: [:new]

  # GET /matters
  # GET /matters.json
  def index
    @matters = Matter.all
  end

  # GET /matters/1
  # GET /matters/1.json
  def show
  end

  # GET /matters/new
  def new
    @matter = Matter.new
  end

  # GET /matters/1/edit
  def edit
  end

  # POST /matters
  # POST /matters.json
  def create
    @matter = Matter.new(matter_params)

    respond_to do |format|
      if @matter.save
        format.html { redirect_to @matter, notice: 'Matter was successfully created.' }
        format.json { render :show, status: :created, location: @matter }
      else
        format.html { render :new }
        format.json { render json: @matter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matters/1
  # PATCH/PUT /matters/1.json
  def update
    respond_to do |format|
      if @matter.update(matter_params)
        format.html { redirect_to @matter, notice: 'Matter was successfully updated.' }
        format.json { render :show, status: :ok, location: @matter }
      else
        format.html { render :edit }
        format.json { render json: @matter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matters/1
  # DELETE /matters/1.json
  def destroy
    @matter.destroy
    respond_to do |format|
      format.html { redirect_to matters_url, notice: 'Matter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_matter
      @matter = Matter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def matter_params
      params.require(:matter).permit(:fixed_fee, :cost, :expect_hours, :lawfirm_id)
    end

    def set_staffing
      @staffings = Staffing.order(:last_name)
    end
end

app/controllers/staffings_controller.rb
class StaffingsController < ApplicationController
  before_action :set_staffing, only: [:show, :edit, :update, :destroy]

  # GET /staffings
  # GET /staffings.json
  def index
    @staffings = Staffing.all
  end

  # GET /staffings/1
  # GET /staffings/1.json
  def show
  end

  # GET /staffings/new
  def new
    @staffing = Staffing.new
  end

  # GET /staffings/1/edit
  def edit
  end

  # POST /staffings
  # POST /staffings.json
  def create
    @staffing = Staffing.new(staffing_params)

    respond_to do |format|
      if @staffing.save
        format.html { redirect_to @staffing, notice: 'Staffing was successfully created.' }
        format.json { render :show, status: :created, location: @staffing }
      else
        format.html { render :new }
        format.json { render json: @staffing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /staffings/1
  # PATCH/PUT /staffings/1.json
  def update
    respond_to do |format|
      if @staffing.update(staffing_params)
        format.html { redirect_to @staffing, notice: 'Staffing was successfully updated.' }
        format.json { render :show, status: :ok, location: @staffing }
      else
        format.html { render :edit }
        format.json { render json: @staffing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /staffings/1
  # DELETE /staffings/1.json
  def destroy
    @staffing.destroy
    respond_to do |format|
      format.html { redirect_to staffings_url, notice: 'Staffing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_staffing
      @staffing = Staffing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def staffing_params
      params.require(:staffing).permit(:first_name, :last_name, :middle_name, :cost_per_hour, :lawfirm_id, :matter_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/matters_helper.rb
module MattersHelper
end

app/helpers/staffings_helper.rb
module StaffingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lawdget</title>
    <%= stylesheet_link_tag    'application' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <%= yield %>
      <br>
      <br>
      <br>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/matters/_form.html.erb
<%= form_for(@matter) do |f| %>
  <% if @matter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@matter.errors.count, "error") %> prohibited this matter from being saved:</h2>

      <ul>
      <% @matter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fixed_fee %><br>
    <%= f.number_field :fixed_fee %>
  </div>
  <div class="field">
    <%= f.label :cost %><br>
    <%= f.number_field :cost %>
  </div>
  <div class="field">
    <%= f.label :expect_hours %><br>
    <%= f.number_field :expect_hours %>
  </div>
  <div class="field">
    <%= f.label :lawfirm_id %><br>
    <%= f.text_field :lawfirm_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/matters/edit.html.erb
<h1>Editing Matter</h1>

<%= render 'form' %>

<%= link_to 'Show', @matter %> |
<%= link_to 'Back', matters_path %>

app/views/matters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Matters</h1>

<table>
  <thead>
    <tr>
      <th>Fixed fee</th>
      <th>Cost</th>
      <th>Expect hours</th>
      <th>Lawfirm</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @matters.each do |matter| %>
      <tr>
        <td><%= matter.fixed_fee %></td>
        <td><%= matter.cost %></td>
        <td><%= matter.expect_hours %></td>
        <td><%= matter.lawfirm %></td>
        <td><%= link_to 'Show', matter %></td>
        <td><%= link_to 'Edit', edit_matter_path(matter) %></td>
        <td><%= link_to 'Destroy', matter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Matter', new_matter_path %>

app/views/matters/new.html.erb
<h1>New Matter</h1>

<div class="row">
  <div class="col-lg-4">

    <h2>Chart</h2>
    <div id="feeChart" style="min-width: 310px; height: 400px; margin: 0 auto"></div>

  </div>
  <div class="col-lg-8">
    <h2 class>Add Staff</h2>
    <div class="row">
      <div class="col-lg-4">
        <h4>Name</h4>
      </div>

      <div class="col-lg-4">
        <h4>Cost per Hour</h4>
      </div>

      <div class="col-lg-4">
        <h4>Expected Hours</h4>
      </div><br><br>
    </div>

    <div class="row">
      <div class="col-lg-4">
        <%= select_tag "Staff", options_for_select(@staffings.collect { |stf| ["#{stf.last_name} #{stf.middle_name[0]}. , #{stf.first_name}", stf.cost_per_hour]}), id: "staffSelect" %>
      </div>
      <div class="col-lg-4">
        <span id="costPerHour"></span>
      </div>
      <div class="col-lg-4">
         <input id='testHours' type='hours' class='matter-hours form-control' placeholder="Expected Hours">
      </div>
    </div>
    <br>
    <br>
    <% @staffings.each do |staffing| %>
<!--       <div class="row">
        <div class="col-lg-4">
          <%= "#{staffing.last_name} #{staffing.middle_name[0]}.  , #{staffing.first_name}" %>
        </div>
        <div class="col-lg-4">
          $<%= staffing.cost_per_hour %>
        </div>
        <div class="col-lg-4">
          <input id='<%="staff#{staffing.id}"%>' type='hours' class='matter-hours form-control' placeholder="Expected Hours">
        </div>
         <br>
      </div> -->
    <% end %>

  </div>
</div>

<script type="text/javascript">


  function costPerHour () {
    $("#staffSelect").on('change', function() {
       var staffCostPerHour = parseInt(($(this).val()));
       $('#costPerHour').text(staffCostPerHour)
    });
  }

  function staffName() {
    var name = $("#staffSelect option:selected").text();
    return name
  }

  function totalCost() {
    $("#testHours").on('change', function() {
      var expectedHours = parseInt($(this).val());
      var cost = parseInt($("#costPerHour").text());
      return cost * expectedHours;
    });
  }

  costPerHour();
  totalCost();

  var chartData = function() {
    var cost = parseInt($("#testHours").val());
    var expectedHours = parseInt($("#staffSelect").val());
    return cost * expectedHours;
  }

  function testJson() {
    return JSON.stringify(
      {"name": staffName(), "data": chartData()}
    );
  }

  // function outPut() {
  //   $("#testHours").on('change',function() {
  //     parseInt($("#costPerHour").val()) * parseInt($("#testHours").val());
  //   });
  // };

</script>

app/views/matters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fixed fee:</strong>
  <%= @matter.fixed_fee %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @matter.cost %>
</p>

<p>
  <strong>Expect hours:</strong>
  <%= @matter.expect_hours %>
</p>

<p>
  <strong>Lawfirm:</strong>
  <%= @matter.lawfirm %>
</p>

<%= link_to 'Edit', edit_matter_path(@matter) %> |
<%= link_to 'Back', matters_path %>

app/views/staffings/_form.html.erb
<%= form_for(@staffing, html: { class: "form-horizontal" }) do |f| %>
  <% if @staffing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@staffing.errors.count, "error") %> prohibited this staffing from being saved:</h2>

      <ul>
      <% @staffing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :first_name, "First Name:", class: "control-label col-sm-3" %>
    <div class="col-sm-6">
      <%= f.text_field :first_name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :last_name, "Last Name:", class: "control-label col-sm-3" %>
    <div class="col-sm-6">
      <%= f.text_field :last_name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :middle_name, "Middle Name:", class: "control-label col-sm-3" %>
    <div class="col-sm-6">
      <%= f.text_field :middle_name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :cost_per_hour, "Cost per Hour:", class: "control-label col-sm-3" %>
    <div class="col-sm-6">
      <%= f.number_field :cost_per_hour, class: "form-control" %>
    </div>
  </div>
  <div class="actions col-sm-offset-3 col-sm-6">
    <%= f.submit class: "btn btn-md btn-primary" %>
  </div>
<% end %>

app/views/staffings/edit.html.erb
<h1>Editing Staffing</h1>

<%= render 'form' %>

<%= link_to 'Show', @staffing %> |
<%= link_to 'Back', staffings_path %>

app/views/staffings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Staffings</h1>

<table class='table table-hover'>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Middle name</th>
      <th>Cost per hour</th>
      <th>Lawfirm</th>
      <th>Matter</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @staffings.each do |staffing| %>
      <tr>
        <td><%= staffing.first_name %></td>
        <td><%= staffing.last_name %></td>
        <td><%= staffing.middle_name %></td>
        <td><%= staffing.cost_per_hour %></td>
        <td><%= staffing.lawfirm %></td>
        <td><%= staffing.matter %></td>
        <td><%= link_to 'Show', staffing %></td>
        <td><%= link_to 'Edit', edit_staffing_path(staffing) %></td>
        <td><%= link_to 'Destroy', staffing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Staffing', new_staffing_path %>

app/views/staffings/new.html.erb
<div class="row">
  <h1 class="col-sm-offset-4 col-sm-6">New Staffing</h1>
</div>
<br>

<%= render 'form' %>

<%= link_to 'Back', staffings_path, class: "" %>

app/views/staffings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @staffing.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @staffing.last_name %>
</p>

<p>
  <strong>Middle name:</strong>
  <%= @staffing.middle_name %>
</p>

<p>
  <strong>Cost per hour:</strong>
  <%= @staffing.cost_per_hour %>
</p>

<p>
  <strong>Lawfirm:</strong>
  <%= @staffing.lawfirm %>
</p>

<p>
  <strong>Matter:</strong>
  <%= @staffing.matter %>
</p>

<%= link_to 'Edit', edit_staffing_path(@staffing) %> |
<%= link_to 'Back', staffings_path %>